apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: manufacturing-monitoring
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: manufacturing-scheduler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kube-state-metrics
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
