apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: manufacturing-monitoring
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: manufacturing-scheduler
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
