apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: manufacturing-monitoring
  labels:
    app.kubernetes.io/name: prometheus-pvc
    app.kubernetes.io/part-of: manufacturing-scheduler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
