apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: manufacturing-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: manufacturing-scheduler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
