apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    url: db:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      encrypt: 'disable'
