apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: manufacturing-app
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: manufacturing-scheduler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
